### ISSUE TITLE
Support for additional logging calls

### ISSUE THREAD

**Issue by lloydwatkin** [bevry/caterpillar#12]
Its been suggested that we use this logger rather than https://github.com/flatiron/winston  (here https://github.com/node-xmpp/node-xmpp/issues/173).

I was wondering whether you'd consider adding standard(-ish) methods of `info`, `debug`, `error`.  This would allow us to use caterpillar/winston without worrying about mismatching APIs?

Even happy to make a PR for it.

**Comment by balupton** [comment]
PR welcome

**Comment by balupton** [comment]
This has been resolved in the upcoming v6
