### ISSUE TITLE
Can't access any docs etc.

### ISSUE THREAD

**Issue by clibu** [bevry/caterpillar#122]
http://master.caterpillar.bevry.surge.sh/docs/classes/logger.html etc. are all showing:

````
This site can’t be reached master.caterpillar.bevry.surge.sh took too long to respond.
````

And also:
````
504 Gateway Time-out
The server didn't respond in time.
````
I'm not having any issues accessing other web sites.

**Comment by balupton** [comment]
Thanka. Ref https://github.com/sintaxi/surge/issues/427

**Comment by clibu** [comment]
Thanks, seems fine now.
